; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "PCSX2"

; Automatically changed by the GitHub action. An example would be "2.0.0"
#define MyAppVersion "PCSX2_VERSION_STRING"
#define MyAppPublisher "PCSX2 Team"
#define MyAppURL "https:/pcsx2.net/"
#define MyAppExeName "pcsx2-qt.exe"

#define MyAppSourceDir "main"
#define MySetupResourceDir "res"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{13CEE6E5-8EB3-47D3-882E-E9DBB6A3251C}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
Compression=lzma2/max
SolidCompression=yes
ArchitecturesInstallIn64BitMode=win64
WizardStyle=modern
MinVersion=10.0.17763
;10.0.22000 ; Windows 11 code just for testing failure on Windows 10

DefaultGroupName={#MyAppName}

DefaultDirName={commonpf64}\{#MyAppName}

OutputDir=PCSX2
OutputBaseFilename={#MyAppName}-v{#MyAppVersion}-windows-x64-installer

; InfoAfterFile=README.txt
UninstallDisplayIcon={app}\{#MyAppExeName},0
SetupIconFile={#MySetupResourceDir}\AppIconLarge.ico
WizardImageFile={#MySetupResourceDir}\AppBanner.bmp
WizardSmallImageFile={#MySetupResourceDir}/AppIconLarge.bmp
AllowNoIcons=yes

[Messages]
WindowsVersionNotSupported=PCSX2 requires Windows 10 (1809) or later. To use this app, please update your operating system.

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkedonce

[Files]
Source: "{#MySetupResourceDir}\VC_redist.x64.exe"; DestDir: {tmp}
Source: "{#MyAppSourceDir}\*"; Excludes: "PUT PCSX2 BUILD HERE.txt"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#MySetupResourceDir}\portable.txt"; DestDir: {app} ; Check: IsPortableInstall;
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Code]    
const
  StandardDescText =
    'All PCSX2 Data will be stored in Documents, separate from the program.';
  PortableDescText =
    'All PCSX2 Data will be stored in the same folder as PCSX2 itself by default.';

var
  OptionPage: TWizardPage;
  StandardRB, PortableRB: TNewRadioButton;
  StandardDesc, PortableDesc: TNewStaticText;
  
procedure DescLabelClick(Sender: TObject);
begin
  if Sender = StandardDesc then StandardRB.Checked := True
  else if Sender = PortableDesc then PortableRB.Checked := True;
end;

procedure InitializeWizard();
begin
  OptionPage := CreateCustomPage(wpWelcome, 'Installation Type', 'How would you like to install PCSX2?');

  // Standard
  StandardRB := TNewRadioButton.Create(OptionPage);
  StandardRB.Parent := OptionPage.Surface;
  StandardRB.Top := ScaleY(8);
  StandardRB.Width := OptionPage.SurfaceWidth;
  StandardRB.Font.Style := [fsBold];
  StandardRB.Caption := 'Standard Installation (Recommended)';
  StandardRB.Checked := True;

  StandardDesc := TNewStaticText.Create(OptionPage);
  StandardDesc.Parent := OptionPage.Surface;
  StandardDesc.Top := StandardRB.Top + ScaleY(24);
  StandardDesc.Left := ScaleX(18);
  StandardDesc.Width := OptionPage.SurfaceWidth - ScaleX(18);
  StandardDesc.Caption := 'Installs to Program Files and saves data to Documents. Best for most users.';
  StandardDesc.OnClick := @DescLabelClick;

  // Portable
  PortableRB := TNewRadioButton.Create(OptionPage);
  PortableRB.Parent := OptionPage.Surface;
  PortableRB.Top := StandardDesc.Top + ScaleY(40);
  PortableRB.Width := OptionPage.SurfaceWidth;
  PortableRB.Font.Style := [fsBold];
  PortableRB.Caption := 'Portable Installation';

  PortableDesc := TNewStaticText.Create(OptionPage);
  PortableDesc.Parent := OptionPage.Surface;
  PortableDesc.Top := PortableRB.Top + ScaleY(24);
  PortableDesc.Left := ScaleX(18);
  PortableDesc.Width := OptionPage.SurfaceWidth - ScaleX(18);
  PortableDesc.Caption := 'Keeps all data inside the app folder. Ideal for USB drives or custom locations.';
  PortableDesc.OnClick := @DescLabelClick;
end;

function IsPortableInstall: Boolean;
begin
  Result := PortableRB.Checked;
end;

function IsStandardInstall: Boolean;
begin
  Result := not IsPortableInstall;
end;

procedure SetDefaultDirName();
begin
  if isPortableInstall = true then
    WizardForm.DirEdit.Text := 'C:\{#MyAppName}'
  else
    WizardForm.DirEdit.Text := ExpandConstant('{commonpf64}') + '\{#MyAppName}';
end;

function ShouldSkipPage(PageID: Integer): Boolean;
begin
  Result := False;
  // Skip Start Menu group selection for Portable mode
  if (PageID = wpSelectProgramGroup) and IsPortableInstall then
    Result := True;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  Page: TWizardPage;
begin
  Page := PageFromID(CurPageID);
  if Page.Caption = 'Installation Type' then
    SetDefaultDirName();
    
  if Page.Caption = 'Select Destination Location' then
  begin
    if Pos('C:\Windows\', WizardForm.DirEdit.Text) <> 0 then
    begin
      MsgBox('Installing PCSX2 in the Windows folder is not advised. Please choose another folder.', mbError, MB_OK);
      Result := false;
      Exit;
    end;
    
    if (isPortableInstall = true) and (Pos('Program Files', WizardForm.DirEdit.Text) <> 0) then
    begin
      MsgBox('Portable install cannot be inside Program Files, please choose another folder.', mbError, MB_OK);
      Result := false;
      Exit;
    end;
  end;
    
  Result := true;
end;

procedure SetMarqueeProgress(Marquee: Boolean);
begin
  if Marquee then
  begin
    WizardForm.ProgressGauge.Style := npbstMarquee;
  end
    else
  begin
    WizardForm.ProgressGauge.Style := npbstNormal;
  end;
end;

[Icons]
; StartMenu
Name: "{group}\{#MyAppName}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"
Name: "{group}\{#MyAppName}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}";

; Desktop
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Registry]
; Local Machine
Root: HKLM; Subkey: "Software\{#MyAppPublisher}"; Flags: uninsdeletekeyifempty
Root: HKLM; Subkey: "Software\{#MyAppPublisher}\{#MyAppName}"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\{#MyAppPublisher}\{#MyAppName}"; ValueType: string; ValueName: "InstallPath"; ValueData: {app}

[Run]
Filename: "{tmp}\VC_redist.x64.exe"; Parameters: "/q /norestart"; \
    Flags: waituntilterminated; \
    StatusMsg: "Installing VC++ 2019-2022 Redistributables... Please Wait."; \
    BeforeInstall: SetMarqueeProgress(True); \
    AfterInstall: SetMarqueeProgress(False)
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
