name: Create Installer

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'The PCSX2 workflow run ID containing the build artifact'
        required: true
        type: string
      artifact_name:
        description: 'The exact PCSX2 build artifact name, e.g. PCSX2-windows-Qt-x64-sha[abc1234]'
        required: true
        type: string
      tag_value:
        description: 'The PCSX2 tag/version. Include the "v" prefix!'
        required: true
        type: string

permissions:
  actions: read
  contents: read

jobs:
  build-installer:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v6

    - uses: actions/download-artifact@v8
      name: Download the PCSX2 build artifact
      with:
        github-token: ${{ secrets.PCSX2_TOKEN }}
        repository: "PCSX2/pcsx2"
        run-id: ${{ inputs.run_id }}
        name: ${{ inputs.artifact_name }}
        path: main

    - name: Grab latest Visual C++ Redistributable Version
      shell: cmd
      run: | 
        cd res
        aria2c -Z "https://aka.ms/vc14/vc_redist.x64.exe"

    - name: Get our version tag
      shell: bash
      run: |
        TAG_NAME=${{ inputs.tag_value }}
        VERSION=${TAG_NAME#v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Inject Release Tag into Installer Script
      shell: bash
      run: |
        sed -i 's/PCSX2_VERSION_STRING/'"$VERSION"'/g' 'PCSX2 Installer.iss'

    - uses: Minionguyjpro/Inno-Setup-Action@36abc9fdddc244a69f4895566fa5b2d8d5854e43
      name: Build the Release
      with:
        path: 'PCSX2 Installer.iss'

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v7
      with:
        if-no-files-found: error
        name: PCSX2-${{ inputs.tag_value }}-windows-x64-installer.exe
        path: |
          PCSX2\PCSX2-${{ inputs.tag_value }}-windows-x64-installer.exe
